services:
  web:
    ports:
      - 5001:5001
      - 24678:24678
    volumes:
      - ./app/src:/app/src
      - ./app/static:/app/static

  # If u want db access
  # db:
  #   ports:
  #     - 5432:5432
