version: "3"
services:
  web:
    build: .
    environment:
      APP_ENV: ${APP_ENV}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: addie
      PGHOST: db
      PGDATABASE: database
      PGPORT: 5432
    ports:
      - 5000:5000
    volumes:
      - ./app/src:/app/src
    restart: always

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: addie
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - addie-db-data:/var/lib/postgresql/data

volumes:
  addie-db-data:
